# Site Info
url:          https://www.mitchlindsay.me
title:        Mitch Lindsay
author:       Mitch Lindsay
description:  The personal portfolio website of Mitch Lindsay

# Collections
collections:
  - summaries
  - jobs
  - technologies
  - schools
  - contacts

# Global Settings
markdown:   kramdown
permalink:  pretty
encoding:   UTF-8

# Server Settings
source:       ./source
destination:  ./static

# Plugins
gems: [
  'bootstrap-sass',
  'font-awesome-sass',
  'jekyll-assets',
  'sass',
  'uglifier'
]

# Assets Pipeline
assets:
  prefix:
    '/assets'
  sources:
    - _assets/fonts
    - _assets/img
    - _assets/scss
    - _assets/js
  compress:
    css:  sass
    js:   uglifier
  features:
    automatic_img_size: false
    automatic_img_alt:  false

# Excluded from build
exclude: [
  'node_modules',
  '.gitignore',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'package.json',
  'Rakefile',
  'README.md'
]
