# Site settings
title: "Mitch Lindsay"
name: "Mitch Lindsay"
email: "work@mitchlindsay.me"
picture: "assets/images/portfolio_picture.jpg"
linkedin: "www.linkedin.com/in/mitchrlindsay"
github: "https://www.github.com/mitchlindsay"

# Build settings
markdown: kramdown
