# Site settings
title: "Mitch Lindsay"
name: "Mitch Lindsay"
email: "mitch.lindsay@tutanota.com"
picture: "assets/images/portfolio_picture.jpg"
linkedin: "https://www.linkedin.com/pub/mitch-lindsay/58/9a9/b37"
github: "https://www.github.com/mitchlindsay"

# Build settings
markdown: kramdown
